---
- name: Check if GVM is installed
  stat: path=~/.gvm/bin/gvm
  register: gvm_installed

- name: Install GVM
  shell: (curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/e5a06b52c76da676e5b42d1f0597e2ba1ee74790/binscripts/gvm-installer) | sh
  when: gvm_installed.stat.exists == false