---
- name: Check homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew_installed

- name: Install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_installed.stat.exists == false

- name: Add homebrew taps
  shell: brew tap {{ item }}
  with_items: "{{ taps }}"

- name: Update homebrew
  shell: brew update

- name: Install homebrew libraries
  homebrew: name={{ item.key }} state=present install_options={{ item.value }}
  with_dict: "{{ brews }}"

- name: Start services at login
  file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
  with_items: 
    - postgresql
    - boot2docker
    - redis

- name: Check homebrew-cask is installed
  stat: path=/usr/local/bin/brew-cask.rb
  register: brew_cask_installed

- name: Install homebrew-cask
  shell: brew install caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask 
  when: brew_cask_installed.stat.exists == false

- name: Check for installed casks
  shell: brew cask list
  register: installed_cask_applications
  ignore_errors: true

- name: Install apps with brew-cask
  shell: brew cask install {{ item }}
  with_items: "{{ applications }}"
  when: "item not in installed_cask_applications.stdout_lines"
