add_newline = false

[package]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false

[line_break]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[git_status]
disabled = true
