setopt append_history
setopt auto_cd
setopt extended_history
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_verify
setopt interactive_comments
setopt vi
unsetopt auto_menu
unsetopt menu_complete

export HISTSIZE=100000
export HISTFILESIZE=100000
export LESS="--hilite-search --long-prompt --raw-control-chars --tabs=4 --no-init --force --quit-if-one-screen -z-1"

# all-in on emacs
export EDITOR="emacs -nw"
export VISUAL="emacsclient -c"
export ALTERNATE_EDITOR="emacs -nw"

# set up `help` command
autoload -Uz run-help
unalias run-help
alias help=run-help

# aliases
alias c="clear"
alias e="emacsclient -c"
alias ls="/usr/local/bin/gls --color=auto"
alias ll="ls -l"
alias g="git"
alias groot='cd "`git rev-parse --show-toplevel`"'
alias ipy='poetry run ipython --TerminalInteractiveShell.editing_mode=vi --InteractiveShell.colors=linux --no-confirm-exit'
alias node='env NODE_NO_READLINE=1 rlwrap node'
alias pgctl='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/log/postgres.log'

## fasd/autojump/z
eval "$(fasd --init auto)"
unalias s
alias j="fasd_cd -d"
alias jj="fasd_cd -d -i"

bindkey '^R' history-incremental-pattern-search-backward
bindkey -v '^?' backward-delete-char
bindkey " " magic-space
bindkey "^[[A" up-line-or-search
bindkey "^[[B" down-line-or-search

export PATH=\
"./node_modules/.bin":\
"$HOME/bin":\
"$HOME/.local/bin":\
"$HOME/.emacs.d/bin":\
$PATH

if [[ $UID == 0 || $EUID == 0 ]]; then
    PROMPT='%B%F{red}%n@%m%F{white}:%F{cyan}%~%f%b$'
else
  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
    autoload -Uz compinit
    compinit
    autoload -U colors && colors
    autoload -Uz vcs_info

    precmd_vcs_info() { vcs_info }
    precmd_functions+=( precmd_vcs_info )
    setopt prompt_subst
    PROMPT=\$vcs_info_msg_0_'%B%F{blue}%n@%m%F{white}:%F{cyan}%~%f%b%(?..%F{red}[%?]%f)$ '
    zstyle ':vcs_info:git*' formats "%B%F{yellow}(%b) "
  fi
fi

[[ -f ~/.keys_env ]] && source ~/.keys_env

